# Generated by Django 4.2.28 on 2026-06-29 13:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.research.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campusonline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("third_party_funding_policy", models.BooleanField()),
            ],
            options={
                "db_table": "research_projectcategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bidding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("short", models.TextField()),
                ("description", models.TextField()),
                ("mode", models.CharField(blank=True, max_length=256, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("running", models.BooleanField()),
                ("start", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("iso", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("street", models.CharField(blank=True, max_length=256, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=256, null=True)),
                ("url", models.CharField(blank=True, max_length=256, null=True)),
                ("telephone", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.CharField(blank=True, max_length=256, null=True)),
                ("active", models.BooleanField()),
                ("patron", models.BooleanField()),
                ("patron_peer_review", models.BooleanField()),
                ("patron_associate_professor", models.BooleanField()),
            ],
            options={
                "permissions": (
                    ("view_funder_non_patron", "View funders that are not a patron"),
                ),
            },
        ),
        migrations.CreateModel(
            name="FunderCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("short", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FunderTypeIntellectualCapitalAccounting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="FunderTypeStatisticsAustria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("iso", models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PartnerTypeIntellectualCapitalAccounting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="PredominantFunder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("active", models.BooleanField()),
                (
                    "funder",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="research.funder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short", models.CharField(blank=True, max_length=256, null=True)),
                ("title", django.contrib.postgres.fields.hstore.HStoreField()),
                ("url", models.URLField(blank=True, null=True)),
                ("abstract", django.contrib.postgres.fields.hstore.HStoreField()),
                ("begin_planned", models.DateTimeField(blank=True, null=True)),
                ("begin_effective", models.DateTimeField(blank=True, null=True)),
                ("end_planned", models.DateTimeField(blank=True, null=True)),
                ("end_effective", models.DateTimeField(blank=True, null=True)),
                ("assignment", models.DateTimeField(blank=True, null=True)),
                ("subprogram", models.TextField(blank=True, null=True)),
                ("publish", models.BooleanField()),
                ("visible", models.BooleanField()),
                (
                    "funder_projectcode",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "ethics_committee",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gender_studies", models.BooleanField()),
                ("clinical_trial", models.BooleanField()),
                ("invesitgator_init", models.BooleanField()),
                (
                    "project_total_requested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "project_total_approved",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "internal_order",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("zmf_usage", models.BooleanField()),
                ("biobank_usage", models.BooleanField()),
                ("biomed_research", models.BooleanField()),
                ("commercial", models.BooleanField()),
                (
                    "edudract_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="research.projectcategory",
                    ),
                ),
                (
                    "co_accountable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campusonline.person",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campusonline.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFunction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMentorContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        default=outpost.django.research.models.MultiLanguage.empty_default
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectPartnerFunction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectResearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("public", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStudy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("public", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), size=None
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("source", models.TextField()),
                ("sci", models.CharField(blank=True, max_length=128, null=True)),
                ("pubmed", models.CharField(blank=True, max_length=128, null=True)),
                ("doi", models.CharField(blank=True, max_length=128, null=True)),
                ("pmc", models.CharField(blank=True, max_length=128, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("imported", models.DateTimeField()),
                ("journal", models.TextField(blank=True, null=True)),
                ("issn", models.CharField(blank=True, max_length=20, null=True)),
                ("collection_publisher", models.TextField(blank=True, null=True)),
                ("collection_title", models.TextField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=50, null=True)),
                ("university", models.TextField()),
                ("case_report", models.BooleanField(null=True)),
                ("impactfactor", models.FloatField()),
                ("impactfactor_year", models.PositiveSmallIntegerField()),
                ("impactfactor_norm", models.FloatField()),
                ("impactfactor_norm_year", models.PositiveSmallIntegerField()),
                ("impactfactor_norm_category", models.TextField()),
                ("impactfactor_norm_super", models.FloatField()),
                ("impactfactor_norm_super_year", models.PositiveSmallIntegerField()),
                ("impactfactor_norm_super_category", models.TextField()),
                ("citations", models.BooleanField(null=True)),
                ("conference_name", models.BooleanField(null=True)),
                ("conference_place", models.BooleanField(null=True)),
                ("conference_international", models.BooleanField(null=True)),
                ("scientific_event", models.BooleanField(null=True)),
                ("invited_lecture", models.BooleanField(null=True)),
                ("keynote_speaker", models.BooleanField(null=True)),
                ("selected_presentation", models.BooleanField(null=True)),
                ("biobank_use", models.BooleanField(null=True)),
                ("bmf_use", models.BooleanField(null=True)),
                ("zmf_use", models.BooleanField(null=True)),
                ("local_affiliation", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationAuthorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="PublicationCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="PublicationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="ResearchType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alternate_name",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        default=outpost.django.research.models.MultiLanguage.empty_default,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        default=outpost.django.research.models.MultiLanguage.empty_default,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "campusonline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campusonline.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        default=outpost.django.research.models.MultiLanguage.empty_default
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoProjectStatus",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="research.projectstatus",
                    ),
                ),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DjangoProjectType",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="research.projecttype",
                    ),
                ),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProviderContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alternate_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "alternate_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "campusonline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="campusonline.person",
                    ),
                ),
                (
                    "serviceprovider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="research.serviceprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationPerson",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("last_author", models.BooleanField()),
                (
                    "authorship",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="research.publicationauthorship",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="campusonline.person",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="research.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationOrganization",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "authorship",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="research.publicationauthorship",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_authorship",
                        to="campusonline.organization",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="research.publication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publication",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.publicationcategory",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campusonline.country",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.publicationdocument",
            ),
        ),
        migrations.CreateModel(
            name="ProjectPerson",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "function",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="persons",
                        to="research.projectfunction",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="campusonline.person",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="persons",
                        to="research.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="event",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.projectevent",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="funders",
            field=models.ManyToManyField(
                db_constraint=False,
                db_table="research_project_funder",
                related_name="projects",
                to="research.funder",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="grant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.projectgrant",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="language",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.language",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="legalbasis",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.legalbasis",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="campusonline.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campusonline.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="research.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="partner_function",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.projectpartnerfunction",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="predominant_funder",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.predominantfunder",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.program",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_management_accountable",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="campusonline.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="research",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.projectresearch",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.projectstatus",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="study",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.projectstudy",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="research.projecttype",
            ),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("short", models.CharField(blank=True, max_length=128, null=True)),
                ("street", models.CharField(blank=True, max_length=128, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=128, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("url", models.CharField(blank=True, max_length=128, null=True)),
                ("telephone", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                ("information", models.TextField()),
                (
                    "typeintellectualcapitalaccounting",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="research.partnertypeintellectualcapitalaccounting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "person",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="knowledge",
                        to="campusonline.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="funder",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.fundercategory",
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.country",
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="typeintellectualcapitalaccounting",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="research.fundertypeintellectualcapitalaccounting",
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="typestatisticsaustria",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="research.fundertypestatisticsaustria",
            ),
        ),
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "person",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="expertise",
                        to="campusonline.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "person",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="education",
                        to="campusonline.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_set",
                        to="research.classification",
                    ),
                ),
                (
                    "persons",
                    models.ManyToManyField(
                        db_constraint=False,
                        db_table="research_classification_person",
                        related_name="classifications",
                        to="campusonline.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiddingEndowment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "bidding",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="endowments",
                        to="research.bidding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiddingDeadline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("time", models.CharField(blank=True, max_length=16, null=True)),
                ("comment", models.TextField()),
                (
                    "bidding",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="deadlines",
                        to="research.bidding",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bidding",
            name="funders",
            field=models.ManyToManyField(
                db_constraint=False,
                db_table="research_bidding_funder",
                related_name="biddings",
                to="research.funder",
            ),
        ),
    ]
