# Generated by Django 5.2.16 on 2026-07-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funder",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("view_funder_non_patron", "View funders that are not a patron"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="fundercategory",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectcategory",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="funder",
            name="patron_associate_professor",
        ),
        migrations.AddField(
            model_name="funder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_set",
                to="research.funder",
            ),
        ),
    ]
