# Generated by Django 2.2.28 on 2024-06-11 15:03

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.research.models


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0078_linz"),
        ("research", "0002_foreign"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
            options={
                "db_table": "research_legal_basis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PredominantFunder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "research_predominant_funder",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectFunction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("active", models.BooleanField()),
            ],
            options={
                "db_table": "research_projectfunction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectPerson",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "research_project_person",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicationPerson",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("last_author", models.BooleanField()),
            ],
            options={
                "db_table": "research_publication_person",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alternate_name",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        default=outpost.django.research.models.MultiLanguage.empty_default,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        default=outpost.django.research.models.MultiLanguage.empty_default,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "campusonline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campusonline.Organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProviderContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alternate_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "alternate_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "campusonline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="campusonline.Person",
                    ),
                ),
                (
                    "serviceprovider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="research.ServiceProvider",
                    ),
                ),
            ],
        ),
    ]
