# Generated by Django 5.2.16 on 2026-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_alter_funder_options_alter_fundercategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bidding",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="biddingdeadline",
            options={"ordering": ("bidding__title",)},
        ),
        migrations.AlterModelOptions(
            name="biddingendowment",
            options={"ordering": ("bidding__title",)},
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="funder",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
