# Generated by Django 5.2.16 on 2026-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research",
            "0003_alter_bidding_options_alter_biddingdeadline_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funder",
            name="category",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="email",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="telephone",
        ),
        migrations.AddField(
            model_name="funder",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
