# Generated by Django 2.2.28 on 2025-01-20 11:21

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import outpost.django.research.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research",
            "0003_legalbasis_predominantfunder_projectfunction_projectperson_publicationperson_serviceprovider_service",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMentorContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        default=outpost.django.research.models.MultiLanguage.empty_default
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        default=outpost.django.research.models.MultiLanguage.empty_default
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
