# Generated by Django 5.2.16 on 2026-08-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_remove_funder_category_remove_funder_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="active",
            field=models.BooleanField(verbose_name="active organization"),
        ),
        migrations.AlterField(
            model_name="funder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_set",
                to="research.funder",
                verbose_name="parent organization",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="patron",
            field=models.BooleanField(verbose_name="research funding agency"),
        ),
        migrations.AlterField(
            model_name="funder",
            name="patron_peer_review",
            field=models.BooleanField(verbose_name="funding agency with peer review"),
        ),
        migrations.AlterField(
            model_name="funder",
            name="typeintellectualcapitalaccounting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.fundertypeintellectualcapitalaccounting",
                verbose_name="wibi classification",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="typestatisticsaustria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research.fundertypestatisticsaustria",
                verbose_name="statistic austria classification",
            ),
        ),
    ]
