# Generated by Django 2.2.28 on 2026-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_projectmentorcontribution_sponsorship'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE research.geldgeber
                        ADD COLUMN aktiv_ja_nein varchar(4) NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE research.geldgeber
                        DROP COLUMN aktiv_ja_nein;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.research_funder;

                        CREATE MATERIALIZED VIEW public.research_funder AS SELECT
                            geldgeber.geldgeber_id AS id,
                            geldgeber.geldgeber_de AS name,
                            geldgeber.strasse AS street,
                            geldgeber.ort AS city,
                            geldgeber.postleitzahl AS zipcode,
                            laender_iso.iso_nummer::integer AS country_id,
                            geldgeber.url,
                            geldgeber.geldgeber_typ_id AS category_id,
                            geldgeber.telefon AS telephone,
                            geldgeber.email,
                            COALESCE(lower(geldgeber.aktiv_ja_nein::text = 'ja'::text), false) AS active,
                            COALESCE(lower(geldgeber.fo_foe_ja_nein::text) = 'ja'::text, false) AS patron,
                            COALESCE(lower(geldgeber.peer_review_assozprof::text) = 'ja'::text, false) AS patron_associate_professor,
                            COALESCE(lower(geldgeber.peer_review_allg::text) = 'ja'::text, false) AS patron_peer_review,
                            geldgeber.wibi_typ_id AS typeintellectualcapitalaccounting_id,
                            geldgeber.statistik_aut_typ_id AS typestatisticsaustria_id
                        FROM research.geldgeber
                        LEFT JOIN research.land
                            ON geldgeber.land_id = land.land_id
                        LEFT JOIN campusonline.laender_iso
                            ON land.iso_alpha3::text = laender_iso.iso_code_3::text
                        WITH DATA;

                        CREATE INDEX research_funder_category_id_idx
                            ON public.research_funder (category_id);

                        CREATE INDEX research_funder_country_id_idx
                            ON public.research_funder (country_id);

                        CREATE UNIQUE INDEX research_funder_id_idx
                            ON public.research_funder (id);

                        CREATE INDEX research_funder_patron_associate_professor_idx
                            ON public.research_funder (patron_associate_professor);

                        CREATE INDEX research_funder_patron_idx
                            ON public.research_funder (patron);

                        CREATE INDEX research_funder_patron_peer_review_idx
                            ON public.research_funder (patron_peer_review);
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.research_funder;

                        CREATE MATERIALIZED VIEW public.research_funder AS SELECT
                                geldgeber.geldgeber_id AS id,
                                geldgeber.geldgeber_de AS name,
                                geldgeber.strasse AS street,
                                geldgeber.ort AS city,
                                geldgeber.postleitzahl AS zipcode,
                                laender_iso.iso_nummer::integer AS country_id,
                                geldgeber.url,
                                geldgeber.geldgeber_typ_id AS category_id,
                                geldgeber.telefon AS telephone,
                                geldgeber.email,
                                COALESCE(lower(geldgeber.fo_foe_ja_nein::text) = 'ja'::text, false) AS patron,
                                COALESCE(lower(geldgeber.peer_review_assozprof::text) = 'ja'::text, false) AS patron_associate_professor,
                                COALESCE(lower(geldgeber.peer_review_allg::text) = 'ja'::text, false) AS patron_peer_review,
                                geldgeber.wibi_typ_id AS typeintellectualcapitalaccounting_id,
                                geldgeber.statistik_aut_typ_id AS typestatisticsaustria_id
                            FROM research.geldgeber
                            LEFT JOIN research.land
                                ON geldgeber.land_id = land.land_id
                            LEFT JOIN campusonline.laender_iso
                                ON land.iso_alpha3::text = laender_iso.iso_code_3::text
                            WITH DATA;

                        CREATE INDEX research_funder_category_id_idx
                            ON public.research_funder (category_id);

                        CREATE INDEX research_funder_country_id_idx
                            ON public.research_funder (country_id);

                        CREATE UNIQUE INDEX research_funder_id_idx
                            ON public.research_funder (id);

                        CREATE INDEX research_funder_patron_associate_professor_idx
                            ON public.research_funder (patron_associate_professor);

                        CREATE INDEX research_funder_patron_idx
                            ON public.research_funder (patron);

                        CREATE INDEX research_funder_patron_peer_review_idx
                            ON public.research_funder (patron_peer_review);
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="funder",
                    name="active",
                    field=models.BooleanField()
                )
            ],
        )
    ]
