# Generated by Django 5.2.16 on 2026-08-28 10:39

from django.db import migrations, models


def copy_classification_ids(apps, schema_editor):
    Classification = apps.get_model(
        "research",
        "Classification",
    )

    Classification.objects.update(classification_id=models.F("id"))


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0005_alter_funder_active_alter_funder_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="classification_id",
            field=models.PositiveIntegerField(
                null=True,
            ),
        ),
        migrations.RunPython(
            copy_classification_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="classification",
            name="classification_id",
            field=models.PositiveIntegerField(
                unique=True,
            ),
        ),
    ]
