# Generated by Django 2.2.28 on 2026-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0005_add_funder_active"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        SET ROLE "api.medunigraz.at";

                        CREATE MATERIALIZED VIEW public.research_country
                        AS SELECT land.land_id AS id,
                            hstore(ARRAY['de'::text, 'en'::text], ARRAY[land.land_de::text, land.land_en::text]) AS name,
                            land.iso_alpha2 AS iso
                           FROM research.land
                        WITH DATA;

                        CREATE UNIQUE INDEX research_country_id_idx ON public.research_country USING btree (id);
                        CREATE INDEX research_country_iso_idx ON public.research_country USING btree (iso);
                    """,
                    reverse_sql="""
                        SET ROLE "api.medunigraz.at";

                        DROP MATERIALIZED VIEW IF EXISTS public.research_country;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="country",
                    name="iso",
                    field=models.CharField(max_length=2, blank=True, null=True),
                )
            ],
        )
    ]
