# Generated by Django 5.2.16 on 2026-09-04 08:28

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0001_initial"),
        ("research", "0007_add_countrygroup_country_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classification",
            options={"ordering": ("classification_id", "level")},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="countrygroup",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="field",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="fundertypeintellectualcapitalaccounting",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="fundertypestatisticsaustria",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="legalbasis",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="predominantfunder",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectevent",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectfunction",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectgrant",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectmentorcontribution",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectpartnerfunction",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectresearch",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projectstudy",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="projecttype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="researchtype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="serviceprovider",
            options={"ordering": ("campusonline",)},
        ),
        migrations.AlterModelOptions(
            name="serviceprovidercontact",
            options={"ordering": ("serviceprovider",)},
        ),
        migrations.RemoveField(
            model_name="classification",
            name="persons",
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="alternate_name",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="notes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovidercontact",
            name="campusonline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="campusonline.person",
                verbose_name="contactperson",
            ),
        ),
    ]
