# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-02 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP INDEX IF EXISTS research_project_id_idx;
            """,
            """
            CREATE UNIQUE INDEX research_project_id_idx ON "public"."research_project" ("id");
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."research_project";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."research_project" AS SELECT
                PROJEKT_ID::integer AS id,
                ORGEINHEIT_ID::integer AS organization_id,
                PROJEKT_TYP_ID::integer AS category_id,
                KURZBEZEICHNUNG AS short,
                hstore(
                    ARRAY['de', 'en'],
                    ARRAY[PROJEKTTITEL_DE, PROJEKTTITEL_EN]
                ) AS title,
                ORG_PARTNER_PROJEKTFUNKTION_ID::integer AS partner_function_id,
                PROJEKTLEITER_ID::integer AS manager_id,
                KONTAKTPERSON_ID::integer AS contact_id,
                PROJEKT_STATUS_ID::integer AS status_id,
                PROJEKT_URL AS url,
                hstore(
                    ARRAY['de', 'en'],
                    ARRAY[ABSTRACT_DE, ABSTRACT_EN]
                ) AS abstract,
                PROJEKTBEGINN_GEPLANT::timestamptz AS begin_planned,
                PROJEKTBEGINN_EFFEKTIV::timestamptz AS begin_effective,
                PROJEKTENDE_GEPLANT::timestamptz AS end_planned,
                PROJEKTENDE_EFFEKTIV::timestamptz AS end_effective,
                VERGABE_ART_ID::integer AS grant_id,
                FORSCHUNG_ART_ID::integer AS research_id,
                VERANSTALTUNG_ART_ID::integer AS event_id,
                STUDIE_ART_ID::integer AS study_id,
                SPRACHE_ID::integer AS language_id,
                STAMMDATEN_UEBERTRAGUNG::timestamptz AS assignment,
                FORSCHUNG_PROGRAMM_ID::integer AS program_id,
                FORSCHUNG_SUBPROGRAMM AS subprogram
            FROM
                research.projekt
            INNER JOIN
                campusonline.personen AS co_p_m
                ON projekt.projektleiter_id::integer = co_p_m.pers_nr::integer
            INNER JOIN
                campusonline.personen AS co_p_c
                ON projekt.kontaktperson_id::integer = co_p_c.pers_nr::integer
            INNER JOIN
                campusonline.organisationen AS co_o
                ON projekt.orgeinheit_id::integer = co_o.nr::integer
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."research_project" AS SELECT
                PROJEKT_ID::integer AS id,
                ORGEINHEIT_ID::integer AS organization_id,
                PROJEKT_TYP_ID::integer AS category_id,
                KURZBEZEICHNUNG AS short,
                hstore(
                    ARRAY['de', 'en'],
                    ARRAY[PROJEKTTITEL_DE, PROJEKTTITEL_EN]
                ) AS title,
                ORG_PARTNER_PROJEKTFUNKTION_ID::integer AS partner_function_id,
                PROJEKTLEITER_ID::integer AS manager_id,
                KONTAKTPERSON_ID::integer AS contact_id,
                PROJEKT_STATUS_ID::integer AS status_id,
                PROJEKT_URL AS url,
                hstore(
                    ARRAY['de', 'en'],
                    ARRAY[ABSTRACT_DE, ABSTRACT_EN]
                ) AS abstract,
                PROJEKTBEGINN_GEPLANT::timestamptz AS begin_planned,
                PROJEKTBEGINN_EFFEKTIV::timestamptz AS begin_effective,
                PROJEKTENDE_GEPLANT::timestamptz AS end_planned,
                PROJEKTENDE_EFFEKTIV::timestamptz AS end_effective,
                VERGABE_ART_ID::integer AS grant_id,
                FORSCHUNG_ART_ID::integer AS research_id,
                VERANSTALTUNG_ART_ID::integer AS event_id,
                STUDIE_ART_ID::integer AS study_id,
                SPRACHE_ID::integer AS language_id,
                STAMMDATEN_UEBERTRAGUNG::timestamptz AS assignment,
                FORSCHUNG_PROGRAMM_ID::integer AS program_id,
                FORSCHUNG_SUBPROGRAMM AS subprogram
            FROM
                research.projekt
            LEFT OUTER JOIN
                campusonline.personen AS co_p_m
                ON projekt.projektleiter_id::integer = co_p_m.pers_nr::integer
            LEFT OUTER JOIN
                campusonline.personen AS co_p_c
                ON projekt.kontaktperson_id::integer = co_p_c.pers_nr::integer
            INNER JOIN
                campusonline.organisationen AS co_o
                ON projekt.orgeinheit_id::integer = co_o.nr::integer
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."research_project";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX research_project_id_idx ON "public"."research_project" ("id");
            """,
            """
            DROP INDEX IF EXISTS research_project_id_idx;
            """,
        ),
    ]

    dependencies = [
        ("research", "0009_publication_imported"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
