# Generated by Django 2.2.26 on 2022-04-19 19:05

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_doxis_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunderTypeIntellectualCapitalAccounting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "research_fundertypeintellectualcapitalaccounting",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FunderTypeStatisticsAustria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "research_fundertypestatisticsaustria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("short", models.CharField(blank=True, max_length=128, null=True)),
                ("street", models.CharField(blank=True, max_length=128, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=128, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("url", models.CharField(blank=True, max_length=128, null=True)),
                ("telephone", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                ("information", models.TextField()),
            ],
            options={
                "db_table": "research_partner",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerTypeIntellectualCapitalAccounting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "research_partnertypeintellectualcapitalaccounting",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="funder",
            options={
                "managed": False,
                "permissions": (
                    ("view_funder_non_patron", "View funders that are not a patron"),
                ),
            },
        ),
    ]
